[DDCE-5194] Play 3.0 upgrade
hmrc/register-trust-protector-frontend pull request #136
Opened 2024-05-03 08:57 UTC by DannyPennington97

2024-05-07 14:34 UTC, machinesleet commented on project/AppDependencies.scala
>    val test: Seq[ModuleID] = Seq(
From this test block I think you can remove scalatest, scalatestplus-play, scalacheck, and wiremock-standalone. Apart from wiremock-standalone they're all provided by bootstrap-test-play-30

2024-05-20 09:05 UTC, frikit requested changes

2024-05-20 09:05 UTC, frikit commented on build.sbt
>      scalacOptions ++= Seq("-feature"),
replace line with 
```scala
scalacOptions ++= Seq(
      "-feature",
      "-Wconf:src=routes/.*:s",
      "-Wconf:cat=unused-imports&src=views/.*:s"
    ),
```

2024-05-20 09:05 UTC, frikit commented on build.sbt
>  addCommandAlias("scalastyleAll", "all scalastyle test:scalastyle")
must be
```scala
addCommandAlias("scalastyleAll", "all scalastyle Test/scalastyle")
```

2024-05-20 09:05 UTC, frikit commented on conf/logback.xml
>  <configuration>
this file suppose to be https://github.com/hmrc/hmrc-frontend-scaffold.g8/blob/main/src/main/g8/conf/logback.xml and replace `new_service.log` with service name with underscores

2024-05-20 09:05 UTC, frikit commented on project/AppDependencies.scala
>      "org.scalatestplus"      %% "scalatestplus-scalacheck" % "3.1.0.0-RC2",
can be updated `"org.scalatestplus"           %% "scalacheck-1-17"          % "3.2.18.0",`

2024-05-20 09:05 UTC, frikit commented on project/build.properties
> +sbt.version=1.9.9
as per platform this must be 1.9.7 to avoid issues

2024-05-20 09:05 UTC, frikit commented on project/plugins.sbt
>  resolvers += Resolver.typesafeRepo("releases")
can be deleted

2024-05-20 09:05 UTC, frikit commented on test/base/SpecBase.scala
> +  val defaultAppConfigurations: Map[String, Any] = Map(
this config must be used in all the places you built `new GuiceApplicationBuilder`

2024-05-20 09:05 UTC, frikit commented on project/plugins.sbt
> +addSbtPlugin("com.timushev.sbt"    %  "sbt-updates"          % "0.6.3")
can be updated

2024-05-20 09:17 UTC, machinesleet commented on project/build.properties
> +sbt.version=1.9.9
there's a fair few completed migrations that have used 1.9.9
is there any issue here beyond longer build times?

2024-05-20 09:23 UTC, frikit commented on project/build.properties
> +sbt.version=1.9.9
oh this works than fine , only issue might be only plugins incompatibility, but it sok leave it here then

2024-05-20 13:01 UTC, frikit approved these changes

2024-05-20 13:03 UTC, merged